export const GET_MERCHANTS = "GET_MERCHANTS"
export const GET_MERCHANTS_SUCCESS = "GET_MERCHANTS_SUCCESS"
export const GET_MERCHANTS_FAIL = "GET_MERCHANTS_FAIL"

export const UPDATE_MERCHANT = "UPDATE_MERCHANT"
export const UPDATE_MERCHANT_SUCCESS = "UPDATE_MERCHANT_SUCCESS"
export const UPDATE_MERCHANT_FAIL = "UPDATE_MERCHANT_FAIL"


export const UPDATE_MEMBER = "UPDATE_MEMBER"
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS"
export const UPDATE_MEMBER_FAIL = "UPDATE_MEMBER_FAIL"

export const DELETE_MEMBER = "DELETE_MEMBER"
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS"
export const DELETE_MEMBER_FAIL = "DELETE_MEMBER_FAIL"
